import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Navbar from "@/components/Navbar";
import "./globals.css";

import "@radix-ui/themes/styles.css";

import { Theme } from "@radix-ui/themes";
import { ThemeProvider } from "next-themes";
import Footer from "../components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider attribute="class">
          {" "}
          <div>
            <Theme>
              <Navbar />
              <div>{children}</div>

              <Footer />
            </Theme>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
